name: Sort notes
on:
  push:
    branches:
      master
  schedule:
  - cron: '0 8 * * 4'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: Set up repository and Compile
      run: |
        npm i
        npx tsc
    - name: run index.js
      run: node index.js
      env:
        ARCWIKI_PASS_SORT_NOTES: ${{ secrets.ARCWIKI_PASS_SORT_NOTES }}
